export const LOG_IN = "LOG_IN";
export const LOG_IN_FAIL = "LOG_IN_FAIL";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";

export const LIST_DEVICES = "LIST_DEVICES";
export const LIST_DEVICES_FAIL = "LIST_DEVICES_FAIL";
export const LIST_DEVICES_SUCCESS = "LIST_DEVICES_SUCCESS";

export const GET_DEVICE = "GET_DEVICE";
export const GET_DEVICE_FAIL = "GET_DEVICE_FAIL";
export const GET_DEVICE_SUCCESS = "GET_DEVICE_SUCCESS";

export const DELETE_DEVICE = "DELETE_DEVICE";
export const DELETE_DEVICE_FAIL = "DELETE_DEVICE_FAIL";
export const DELETE_DEVICE_SUCCESS = "DELETE_DEVICE_SUCCESS";

export const ADD_DEVICE = "ADD_DEVICE";
export const ADD_DEVICE_FAIL = "ADD_DEVICE_FAIL";
export const ADD_DEVICE_SUCCESS = "ADD_DEVICE_SUCCESS";
